# Site settings
title: Alessandro Nessi
description: System Administrator and CS Student
baseurl: "/alessandronessi.com" # the subpath of your site, e.g. /blog
url: "https://alessandronessi.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alessandro Nessi
user_description: System administrator with a strong passion for cybersecurity and experience in managing IT infrastructures, networks, and open source solutions. I combine technical skills with a hands-on approach to build secure, high-performing, and scalable environments. Constantly learning, I approach every project with precision and curiosity.
user_title: System Administrator & CS Student
email: io@alessandronessi.com
# twitter_username: lorem_ipsum
#instagram_username: 
#facebook_username:
linkedin_username: alessandro-nessi
github_username:  daspolo
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

